= Pricing and Benchmark Information

This is a partialy compliant TPC Pricing Standard Specification version 2.5.0

You can find the original source to this at http://www.tpc.org/tpc_documents_current_versions/pdf/pricing_v2.5.0.pdf[TPC Pricing, 2.5.0]



== Specification Precedence

[1.1] If there is a conflict between the Benchmark Standard and the Pricing Specification, the Pricing
Specification is the controlling document.

[1.2] If there is a conflict that is not explicitly called out in the Benchmark Standard, the pricing
specification wording prevails.

[1.3]  If there is language in the pricing specification and not in the Benchmark Standard, the pricing
specification prevails.

[1.4] If there is language in the Benchmark Standard and not in the pricing specification, the Benchmark
Standard prevails.

=== General Guidelines

The purpose of our benchmarks is to provide relevant, objective information to industry users.
To achieve that purpose and to adhere to TPC benchmark standards, we require that Pricing:

1) Is no lower than what would be quoted to any Customer from the date of publication of the
FDR until the Result ceases to be an Active Result.

2) Is actively used by the vendor in the market segment that the Pricing Conventions or
represents (e.g., small business customers, or large corporations, depending on the type of
system being priced).

3) A significant number of Customers in the market segment that the Pricing Conventions or
represents would plausibly receive in a Purchase Agreement.

=== Relevent Terms (not exhaustive)

[Archive Operation Requirement] - The period of time for which data generated by the Priced
Configuration as required by the benchmark specification must be maintained in on-line storage.

[Response Time for Problem Recognition] - The period of time it takes from Customer request
until an active process is underway to classify the problem and, if it is at a level that would qualify
as a Failure in this document, initiate the isolation and eventual resolution of the problem. There
must be ownership of the problem. Simply having it in a queue is not sufficient. Direct
interaction with the Customer or their computer must underway. The resumption of Customer
operations need not be guaranteed within the response period.

[Failure] - A condition that prevents the system under test from performing benchmark operations
at the performance and functional levels required by the Benchmark Standard and claimed in the
FDR.


[Field Replaceable Unit (FRU)] - A Component of the Priced Configuration that must be
removed and/or installed by personnel of the maintenance provider.
Fix - Any resolution (including “workarounds”) that restores the Customer’s Application to
normal operation.

[Priced Configuration]- The Line Items to be priced as defined in the Benchmark Standard.

[Priced Currency] – A currency that a Customer commonly uses in the Priced Locale. The Priced
Currency must be identified by an ISO Currency Code.
[NOTE] The intent is the Priced Currency is one commonly used in the Priced Locale.

[Priced Locale] – The geographical area where the entire Priced Configuration, including all Line
Items and associated maintenance, are Generally Available in the Priced Currency(s) and from
the documented Pricing Sources.

[Pricing] - The methods and documentation used to obtain a Total Price for the Priced
Configuration

[Pricing Convention] - The algorithm or process used by a vendor to set or compute prices. There
can be many Pricing Conventions within a single vendor pertaining to the same products or
group of products. Pricing Conventions are often aimed at specific markets.

[Pricing Methodology ]- The methodology to be used to calculate the price and the
price/performance Result of the Benchmark Standard.

[Pricing Model] – A representation of the relationship between the Regions used for the driver
and System Under Test in both the Measured Configuration and the Priced Configuration.

[Pricing Period] – The period of time for which the pricing of all hardware (purchase price),
software (license charges), Licensed Compute Services, and hardware/software maintenance
must be priced. The Pricing Period must be defined in the Benchmark Standard.

[Pricing Source] - A group or individual that would normally generate a price quotation for the
Sales Channel specified in the FDR. For example, if the Sales Channel is a web-based tool that
automatically generated a price quotation, then the Pricing Source is that tool.

[Pricing Spreadsheet] - The Pricing Spreadsheet is a table that lists the individually priced Line
Items of the Priced Configuration, including the Pricing Source of the price, quantities, the
computation of extended price, maintenance, and any applied Discounts.

== Pricing Methodology

=== 1.1 Pricing Methodology
The intent of this section is to define the methodology to be used to calculate the price and the
price/performance Result of the Benchmark Standard.

=== 1.2 Comparability
The different Pricing Methodologies are not comparable. A Benchmark Standard may specify
one and only one Pricing Methodology.

=== 1.3 General Pricing Methodology Requirements
The following requirements are applicable to all Pricing Methodologies.

===== 1.3.1 The price listed must be the full price a Customer would pay for new Physically Acquired
hardware or the acquisition of Licensed Compute Services, and new software licenses. Any other
acquisition models are not allowed.

===== 1.3.2 Pricing must be for a one-time, stand-alone purchase. Pricing cannot be based upon the
acquisition or licensing from past, present, or future Customer purchases.

===== 1.3.3 The Pricing must reflect the price for the acquisition of the system under test, the licensing of
software used in the benchmark, and if applicable the contracts for maintenance.

===== 1.3.4 The prices must be disclosed in a Line Item fashion using a Priced Currency of a Priced Locale
where the Priced Configuration is Generally Available.

===== 1.3.5 The Pricing for both the Physically Acquired hardware or the acquisition of Licensed Compute
Services is based upon the Priced Configuration.

===== 1.3.6 All Pricing must be good at the time of publication. Price changes are subject to rules for revision
as stated in Clause 5.6.

===== 1.3.7 The Line Items to be priced are defined in the Benchmark Standard as the Priced Configuration
and if applicable, the maintenance on those Line Items.

===== 1.3.8 The performance of the Measured Configuration and the Priced Configuration must be
equivalent.

===== 1.3.9 All hardware or Licensed Compute Services, software and support used in the calculations must
be Orderable by any Customer on the Availability Date.

===== 1.3.10 A Non-Disclosure Agreement or other restriction that prevents any Customer from ordering any
priced Line Item disclosed in an FDR is not allowed.
Comment: The presence of an NDA does not mean that obtaining the Pricing is exclusionary.
The actual NDA needs to be examined to determine exclusionary pricing. For instance, there are
types of NDA's in an End-User Licensing Agreement (EULA) which prevent end users from
disclosing certain things learned about a product.

===== 1.3.11 Local Pricing and Discount structures must be Available in each Priced Locale for which the
Results are published.
===== 1.3.12 For Line Items, or associated maintenance, that are priced using a Non-Local Currency, a price
quote must be provided by the Pricing Source, regardless if the Pricing Source is the Sponsor or a Third
Party.
===== 1.3.13 If one or more Line Items are priced using a Priced Currency that is different from the Primary
Currency, Currency Conversion must be applied to these Line Items. If more than one Line Item uses
the same Priced Currency, Currency Conversion must be applied to the total amount of all Line Items
using that Priced Currency, rather than to the price of each of those Line Items or to a sub-total amount
of a subset of those Line Items.

===== 1.3.14 Currency Conversions
Results using Currency Conversion must do the following:
• All Discounts must be applied prior to any Currency Conversion
• The Discount must be in the same Priced Currency as the Line Item(s)
• The Sponsor must use the same Currency Conversion Source for all Currency Conversions
• Currency Conversion must be done no earlier than twenty-one (21) days prior to the Result
submission
• All Currency Conversions must be done no earlier than the latest price quote date
• All Currency Conversions must occur on the same date
• The date of the Currency Conversion must be disclosed in the Full Disclosure Report
