= Specification Precedence

[1.1] If there is a conflict between the Benchmark Standard and the Pricing Specification, the Pricing
Specification is the controlling document.

[1.2] If there is a conflict that is not explicitly called out in the Benchmark Standard, the pricing
specification wording prevails.

[1.3]  If there is language in the pricing specification and not in the Benchmark Standard, the pricing
specification prevails.

[1.4] If there is language in the Benchmark Standard and not in the pricing specification, the Benchmark
Standard prevails.

=== Relevent Terms (not exhaustive)

[Archive Operation Requirement] - The period of time for which data generated by the Priced
Configuration as required by the benchmark specification must be maintained in on-line storage.

[Response Time for Problem Recognition] - The period of time it takes from Customer request
until an active process is underway to classify the problem and, if it is at a level that would qualify
as a Failure in this document, initiate the isolation and eventual resolution of the problem. There
must be ownership of the problem. Simply having it in a queue is not sufficient. Direct
interaction with the Customer or their computer must underway. The resumption of Customer
operations need not be guaranteed within the response period.

[Failure] - A condition that prevents the system under test from performing benchmark operations
at the performance and functional levels required by the Benchmark Standard and claimed in the
FDR.


[Field Replaceable Unit (FRU)] - A Component of the Priced Configuration that must be
removed and/or installed by personnel of the maintenance provider.
Fix - Any resolution (including “workarounds”) that restores the Customer’s Application to
normal operation.

[Priced Configuration]- The Line Items to be priced as defined in the Benchmark Standard.

[Priced Currency] – A currency that a Customer commonly uses in the Priced Locale. The Priced
Currency must be identified by an ISO Currency Code.
[NOTE] The intent is the Priced Currency is one commonly used in the Priced Locale.

[Priced Locale] – The geographical area where the entire Priced Configuration, including all Line
Items and associated maintenance, are Generally Available in the Priced Currency(s) and from
the documented Pricing Sources.

[Pricing] - The methods and documentation used to obtain a Total Price for the Priced
Configuration

[Pricing Convention] - The algorithm or process used by a vendor to set or compute prices. There
can be many Pricing Conventions within a single vendor pertaining to the same products or
group of products. Pricing Conventions are often aimed at specific markets.

[Pricing Methodology ]- The methodology to be used to calculate the price and the
price/performance Result of the Benchmark Standard.

[Pricing Model] – A representation of the relationship between the Regions used for the driver
and System Under Test in both the Measured Configuration and the Priced Configuration.

[Pricing Period] – The period of time for which the pricing of all hardware (purchase price),
software (license charges), Licensed Compute Services, and hardware/software maintenance
must be priced. The Pricing Period must be defined in the Benchmark Standard.

[Pricing Source] - A group or individual that would normally generate a price quotation for the
Sales Channel specified in the FDR. For example, if the Sales Channel is a web-based tool that
automatically generated a price quotation, then the Pricing Source is that tool.

[Pricing Spreadsheet] - The Pricing Spreadsheet is a table that lists the individually priced Line
Items of the Priced Configuration, including the Pricing Source of the price, quantities, the
computation of extended price, maintenance, and any applied Discounts.
