= Transaction Pricing

[[source, tpc]]
http://www.tpc.org/tpcc/[transaction processing council]
http://www.tpc.org/tpc_documents_current_versions/pdf/pricing_v2.5.0.pdf[v2.5.0, pdf]


== Pricing Terms

[Archive Operation Requirement] - The period of time for which data generated by the Priced
Configuration as required by the benchmark specification must be maintained in on-line storage.

[Available] – The Line Item is Orderable and shipping to Customers in the Priced Locale.

[Availability Date] - The date when all Line Items of the Priced Configuration are Generally
Available.

[Benchmark Special Pricing] - A price that is submitted for publication that uses methods or
values that would not likely be found in an actual Purchase Agreement with a Customer

[Commercially Available Product] - A product that:
1. Is Orderable,
2. Is maintained as defined in this specification,
3. Has a non-zero price for at least one of purchase, license or maintenance support, and
4. Is designed for Customer uses other than running the benchmark.

[Orderable] - A method exists for the specified Sales Channel and a Customer to establish a
Purchase Agreement for the product at a specific price.

[Part Number] - An alphanumeric string used by a supplier to uniquely identify a Line Item of a
Priced Configuration. The Sales Channel should be able to identify the Line Item by the Part
Number when generating a price.

[Physically Acquired] - The one-time purchase of the Priced Configuration to be installed on a
customer’s premises, i.e. on-prem.

[Pre-Publication Board] - The Pre-Publication Board as defined by the TPC Policies.
[Price Performance] – The ratio of the Total Price over the primary metric for performance, as
defined by the Benchmark Standard.

[Priced Configuration]- The Line Items to be priced as defined in the Benchmark Standard.

[Priced Currency] – A currency that a Customer commonly uses in the Priced Locale. The Priced
Currency must be identified by an ISO Currency Code.
[NOTE] The intent is the Priced Currency is one commonly used in the Priced Locale.

[Priced Locale] – The geographical area where the entire Priced Configuration, including all Line
Items and associated maintenance, are Generally Available in the Priced Currency(s) and from
the documented Pricing Sources.

[Pricing] - The methods and documentation used to obtain a Total Price for the Priced
Configuration

[Pricing Convention] - The algorithm or process used by a vendor to set or compute prices. There
can be many Pricing Conventions within a single vendor pertaining to the same products or
group of products. Pricing Conventions are often aimed at specific markets.

[Pricing Methodology ]- The methodology to be used to calculate the price and the
price/performance Result of the Benchmark Standard.

[Pricing Model] – A representation of the relationship between the Regions used for the driver
and System Under Test in both the Measured Configuration and the Priced Configuration.

[Pricing Period] – The period of time for which the pricing of all hardware (purchase price),
software (license charges), Licensed Compute Services, and hardware/software maintenance
must be priced. The Pricing Period must be defined in the Benchmark Standard.

[Pricing Source] - A group or individual that would normally generate a price quotation for the
Sales Channel specified in the FDR. For example, if the Sales Channel is a web-based tool that
automatically generated a price quotation, then the Pricing Source is that tool.

[Pricing Spreadsheet] - The Pricing Spreadsheet is a table that lists the individually priced Line
Items of the Priced Configuration, including the Pricing Source of the price, quantities, the
computation of extended price, maintenance, and any applied Discounts.

[Region] – An area defined by the Line Item provider.

[List Price] - The price, stated in a Priced Currency, for which any Customer could purchase one
unit of a Line Item from a Sales Channel without any other purchase (other than specific
prerequisite or other required products that are documented in association with the product).

[Field Replaceable Unit (FRU)] - A Component of the Priced Configuration that must be
removed and/or installed by personnel of the maintenance provider.
Fix - Any resolution (including “workarounds”) that restores the Customer’s Application to
normal operation.

[Formatted Capacity] - the capacity of a durable media device as defined by the manufacturer of
the device.

[Response Time for Problem Recognition] - The period of time it takes from Customer request
until an active process is underway to classify the problem and, if it is at a level that would qualify
as a Failure in this document, initiate the isolation and eventual resolution of the problem. There
must be ownership of the problem. Simply having it in a queue is not sufficient. Direct
interaction with the Customer or their computer must underway. The resumption of Customer
operations need not be guaranteed within the response period.


[Generally Available] - A product is Available to any Customer.

[ISO Currency Code] – An officially recognized ISO 4217 currency identified by a 3-letter currency
code. The ISO codes for each currency can be obtained from the Internet or the TPC
Administrator.

[Licensed Compute Services] - Publicly offered processing, storage, network, and software services
that are hosted on remote computer servers accessed via a Wide Area Network (e.g. the Internet).
A Customer pays a license fee to the Licensed Compute Services vendor for the use of the
processing, storage, network, and software services. The Licensed Compute Services are not
located or installed on a customer's premises.

[Discount] - A reduction in price, stated in a Priced Currency, from the List Price of a Line Item or
group of Line Items.

[Failure] - A condition that prevents the system under test from performing benchmark operations
at the performance and functional levels required by the Benchmark Standard and claimed in the
FDR.

[Full Disclosure Report (FDR)] - See definition in official TPC Policies document.

[Field Replaceable Unit (FRU)] - A Component of the Priced Configuration that must be
removed and/or installed by personnel of the maintenance provider.

[Component] – A product, Licensed Compute Service, maintenance, or license without any specific
relationship to whether it is a specific Line Item. For example, a power cord is a Component that
may be separately priced as a Line Item with a Part Number or may be included in the price of a
larger Component.

[Continuous Operation Requirement] - The period of time when the Priced Configuration must
be able to support the full operation at the performance levels claimed in the Benchmark
Standard.
[Conversion Rate] – The conversion ratio between two ISO Currencies on a given date, as
published by the Currency Conversion Source.

[Currency Conversion] – The conversion of a monetary amount from a Priced Currency to the
Primary Currency using the associated Conversion Rate.

[Currency Conversion Source] – The TPC approved source for calculating all currency Conversion
Rates. The Currency Conversion Source and the process for determining the Conversion Rate
can be obtained from the TPC Administrator.

[Customer] - Any individual or business, in the Priced Locale, that could plausibly and legally
purchase the products listed in the FDR.

[Customer Application] - The Customer written software required to implement the TPC
Benchmark workload.

[Customer Replaceable Unit (CRU)] - A Component of the Priced Configuration that can be
removed and installed by the customer. CRUs may be serviced as if they are FRUs.
Defect - A behavior of the system that prevents the normal operation of the Customer’s
Application.
