= Central Dogma

I believe our capacity to provide opportunities for cooperation within such a competitive sector will not only help but increase the rate of adoption going forward.
Such an intricate problem that we are solving requires a careful appreciation for the intricate interplay of intercontinental trade.
However, we can't let too many details cloud the path.
This article describes more of the theory that we are applying in order to achieve something we call legal parity.

As we have previously outlined, there are three sorts of smart contracts:

* functional
* equivalent
* parity

Functional being that it posses an enforcement mechanism to induce behavior in a programmed mechanism, e.g.
an escrow contract.
Equivalent would be where your contractual rights are enforceable, such as a loan that defaults asserting your rights.
Parity would mean that it does the exact behavior of actual legal contracts, in that it also involves 3rd parties into the process, e.g.
insurance companies.
Now that we have the terminology to be able to express the legaliness, we can move onto the network itself.
First, let's define what an effective network is, as that is our ultimate goal: none of this will be useful if the network itself is not an effective regime.
The effectiveness of any network or regime (Barrett 2003) is a function of three factors:

* The ambition of its provisions
* The level of participation between actors
* The degree to which actors comply with this framework

In designing version 2 of the protocol we had to set forth some design criteria to be able to model not only user behavior but also to help in planning long term priorities in terms of what we should focus on so that we may realize this.
Taking a mathematical approach to smart contract design is useful in this attempt as it provides us with criteria that we can and can not do.

____
...that a rule constitutes a legal obligation and that compliance is therefore required rather > than merely optional .`" (Hart 1994)
____

Much is said about "`equivalence`" as it relates to the digitization of shipping documents.
Such that the term '`functionally equivalent`' is used in the literature (Goldby 2012) to imply a sort of symmetry to these issues of physicality and possession.
Our approach is radically different: we do not set out to provide for a symmetrical basis for all legal contracts, in fact, our system uses a devolved, that is to say, "`federated`", a model of interlocking networks, and consortiums and a concept we call composability.
Objectives

(i) the promotion of certainty and predictability;
(ii) the promotion of uniformity of application;
(iii) the protection of democratic ideals and ensuring of jurisprudential deliberation, and;
(iv) the retention of efficiency.

== Equivalence vs. Partial Equivalence

We can determine that there lie two base units for the legal system through leximetric analysis, that is to say, there are units of obligatory execution and units of voluntary execution.
This means that there are things you do on your own, and this that you do because you were coerced into doing or your agency has been impaired (e.g.
imprisonment.
We take these units (e.g.
mechanisms for enforcement) and quantify them so that we may determine the necessary capabilities of specific EDI transaction Statement of Definitions transitive (the start of a chain of precedence relations must precede the end of the chain antisymmetric (no two different elements precede each other), reflexive (each element is comparable to itself)

equivalence relation as defined mathematically;

a = a (reflexive property) a = b then b = a a = b and b = c then a = c (transitive property)

partial equivalence as defined mathematically aRb then bRa (symmetry)

if aRb and bRc then aRc (transitivity)

[discrete]
==== Classifying legal mechanisms in terms of mathematical properties

A similar approach applied for automating security audits So these Properties listed above are the "`relations`" of classification upon which we then determine how the legal obligations are arranged, which will then determine what it can do and can not do in the protocol.
This portion of the protocol is called the "`mapping engine`", and is one of the solutions that will enable global adoption, as it represents a legal parity, not a functionally equivalent contract.
The Main Classifiers used in determining protocol capabilities are: Symmetry Transitivity Reflexive

== Additional Assessment Techniques of Realizing Legal Parity

[discrete]
==== Leximetric Analysis

When do drafters of legal instruments specify details and when do they not?
(i) That statute length varies systematically across countries, partially controlling for substance;
(ii) that other legal instruments, such as judicial opinions and contracts, are longer in countries with long statutes;
and (iii) that both of the above are correlated with a large lawyer population.
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=456520 Metholodigcal

System based design methodology in designing and understanding the legal implications of actions and which to give weight to.
This list is basically a filter for determining which primitive is applicable to which law, i.e.
this is part of the mapping engine we have developed.

Legal Patterns for finding important laws We use the term "`pattern`" meaning relevant to our protocol, and "`anti-pattern`" to represent a more subjective interpretation or one that is hard to automate to determine should it be included or not.

=== Patterns

Law that addresses a problem that has not been defined Law that addresses a problem that no longer exists The law addresses more than one problem Law that has no stated purpose The language of the law is vague or complex Law is unable to achieve its stated goal

=== Anti-Patterns

Laws that address problems that have not been defined Laws that address problems that no longer exist Laws that address more than one problem in different domains Laws that lack a stated, measurable problem solving the goal, or purpose Laws that fail to achieve their goal or lack stated goals Laws that lack a citation of references Laws whose burdens are greater than their problem-solving benefit Laws whose problem-solving benefit and burdens are equal Laws whose results cannot be measured Laws that interfere with other laws Laws that duplicate other laws Requires Review Laws that are not enforced* Laws that violate human rights* Laws that are overly vague or complex* Laws that have not undergone QA analysis within a specified time frame Now that we have established legal patterns and a legal classified, we can begin to map out how these relationships present themselves, either by acting upon, being acted upon, events, etc.

*Primitives Layer* Primitives List of Legal Primitive Mechanisms PrimitiveEvent ExercisePrimitive AllocationPrimitive ContractFormationPrimitive ExecutionPrimitive InceptionPrimitive ObservationPrimitive QuantityChangePrimitive ResetPrimitive TermsChangePrimitive TransferPrimitive ExecutionPrimitive

Specification of the primitive event for execution, with '`after`' state being an ExecutionState and the '`before`' state being Null.
The '`before`' ExecutionState (0...0) The 0 cardinality reflects the fact that there is no execution in the before the state of an execution primitive.
Think of this as the "`genesis`" point.
after ExecutionState The after state corresponds to the execution between the parties.
In the case of execution on a contractual product, some additional characteristics may need to be specified to get a fully-formed contract, for instance when the executing party acts as an agent, as is the case in an allocation scenario.
This is the purpose of the ContractFormation primitive event.

==== ContractFormationPrimitive

@dev this design pattern is different in that it does not bundle together execution of the contract and formation of the contract, similar to the way a proxy contract works.
The design pattern for this is to better provide for atomic primitives.
Our purposes do not need such atomicity, as they are contractual products.
ExecutionPrimitive + ContractFormationPrimitive = atomic financial primitive InceptionPrimitive = contractual product primitive [see jEDI contract below] Specification of the primitive event for the formation of a contract, with '`before`' state being an '`ExecutionState`' and '`after`' state being a '`PostInceptionState`'.

==== AllocationPrimitive

The primitive event to represent a split/allocation of a trade.
As part of this primitive event the type of trade, either execution or a contract, does not get altered.
In the case of an execution, the further transformation of each split execution into a contract will be the purpose of the ContractFormation primitive.

==== Primitive Example

example workflow of a contractual product condition ContractType: if AllocationPrimitive exists and before \-> execution exists then after \-> originalTrade \-> execution exists and after \-> allocatedTrade \-> execution exists and after \-> allocatedTrade \-> contract is absent condition ContractType: if AllocationPrimitive exists and before \-> contract exists then after \-> originalTrade \-> contract exists and after \-> allocatedTrade \-> contract exists and after \-> allocatedTrade \-> execution is absent

=== ExercisePrimitive

exerciseTiming which is deemed as associated to a request for exercise that is meant to take place, as opposed to the actual exercise event.
Similar to how in FpML an OptionExercise is constructed.
FpML 5.5 Inception Primitive The primitive event for the inception of a new contract between parties.
Observation Primitive A class to specify the primitive object to specify market observation events, which is applicable across all asset classes.
Quantity Change Primitive The primitive event represents a change in quantity or notional.
Reset Primitive The primitive event represents a reset.
Terms Change Primitive The primitive event represents change(s) to the contractual terms and the clearing submission and acceptance process.
Transfer Primitive

A class to specify the transfer of assets between parties, those assets being either cash, securities, or physical assets (such as freight or an asset held by a bailee relationship such as warehouse receipts).
This class combines components that are cross-assets (settlement date, settlement type, status, ...) and some other which are specialized by asset class (e.g.
the payer/receiver amount and cashflow type for a cash transfer, the transferor/transferee, security indication, quantity, and asset transfer type qualification for the case of security).
Workflow for Contractual Product (e.g.
Forward Contracts)

Example Workflow if WorkflowStep \-> businessEvent \-> primitives \-> inception \-> after \-> contract only exists &nbsp;then WorkflowStep \-> businessEvent \-> primitives \-> inception \-> after \-> contract else if WorkflowStep \-> businessEvent \-> primitives \-> quantityChange \-> after \-> contract exists &nbsp;
&nbsp;then WorkflowStep \-> businessEvent \-> primitives \-> quantityChange \-> after \-> contract &nbsp;else WorkflowStep \-> businessEvent \-> primitives \-> inception \-> after \-> contract &nbsp;as "Contract"
