:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:
:page-pagination:

:doctype: book

Excluded vs.
Exempt Commodity

Charatericiscs:

Non-Fungible (to the extent of varying underlying assets, semi-standardized contractual framework)

Ownership of the commodity can be conveyed in some manner, and the commodity can be consumed.j

Transfer of ownership includes transfer of intangible commodities, such that a contract that transfers ownership of intangible contruactual rights

'''

Aiding and abetting cases against smart contract coders may also implicate temporal issues that do not arise in typical aiding and abetting cases, where the aider and abettor's conduct occurs contemporaneously with the primary violator's conduct.
In the

_Thakkar _complaint, the CFTC emphasized that Thakkar's relationship with Trader A continued as Trader A engaged in spoofing.
Smart contract coders may create code and make it available for use by others without necessarily knowing who is using the smart contract or why they are using it.
Since most blockchain and smart contract projects are open source, the functionality that transforms a legitimate smart contract into one that triggers regulatory concerns may have been added by a developer who cannot be identified, at least without significant forensic analysis.
There may also be cases where the transformation of the smart contract is incremental with different programmers involved at various stages.
Determining the point where the smart contract became problematic, and who added that code, may be challenging.
Indeed, the coder's substantive involvement with a smart contract may conclude long before others begin trading on their protocol.
While smart contract coders may anticipate that activity, and may profit from it, they may not be "`aware`" of the activity in the traditional sense.
At a minimum, it will not be easy for the CFTC to build its case, and the Commission may need to rely on an expansive concept of knowledge to prevail.

==== Black Sunday Attack - DirecTV

Example of a piece-meal hack that comes together only at the end

https://www.wired.com/2008/05/tarnovsky/?currentPage=all
