|===
| Requirement | FreightTrust | DCOs

| RuleBook
| Yes
| Yes

| Conflicts of Interest
| Yes
| Yes

| Novation
| Yes
| Yes

| Collateral (inc.
margin)
| No
| Yes

| Netting Arrangements
| No
| Yes

| Dispute Resolution
| Yes
| Yes

| Emergency Rules
| Yes
| Yes

| Collateralized
| Always 100%
| up to 100%
|===

###

###

=== Digital Asset Collateral

(a) With respect to any digital asset Collateral, including, but not limited to, Bitcoin, which is or may be credited to any Clearing Participant's Member Property Account, the following terms and conditions shall apply: (i) For purposes of creating a "`security entitlement`" as such term is defined in Section 8-102(a)(17) of the UCC, the Clearinghouse and the Clearing Participant agree that: (1) the digital asset Collateral shall be treated as a "`financial asset`" as such term is defined in Section 8-102(a)(9) of the UCC;
and (2) each Clearing Participant shall be treated as an "`entitlement holder`" as such term is defined in Section 8-102(a)(7) of the UCC.

(ii) Each Clearing Participant acknowledges that the Clearinghouse is a "`securities intermediary`" as such term is defined in Section 8-102(a)(14) of the UCC.

(iii) Any digital asset Collateral which a Clearing Participant desires be credited to such Clearing Participant's Member Property Account shall be transferred to a digital asset wallet designated by the Clearinghouse and upon such transfer the Clearinghouse shall indicate by book entry that such digital asset Collateral, less applicable transfer costs and fees, has been credited to such Member Property Account.
(b) With respect to any digital asset Collateral, including, but not limited to, Bitcoin, which is or may be credited to any Customer Account, the following terms and conditions shall apply:

(i) For purposes of creating a "`security entitlement`" as such term is defined in Section 8-102(a)(17) of the UCC, the Clearinghouse and the Customer and the relevant FCM Clearing Participant all agree that:

(1) the digital asset Collateral shall be treated as a "`financial asset`" as such term is defined in Section 8-102(a)(9) of the UCC;
and

(2) each FCM Clearing Participant shall be treated as an "`entitlement holder`" as such term is defined in Section 8-102(a)(7) of the UCC.

(ii) Each Customer and each FCM Clearing Participant acknowledges that the Clearinghouse is a "`securities intermediary`" as such term is defined in Section 8-102(a)(14) of the UCC.

(iii) Any digital asset Collateral which an FCM Clearing Participant desires be credited to any of such FCM Clearing Participant's Customer Accounts shall be transferred to a digital asset wallet designated by the Clearinghouse and upon such transfer the Clearinghouse shall indicate by book entry that such digital asset Collateral, less applicable transfer costs and fees, has been credited to any of such Customer Accounts.
(c) The Clearinghouse shall have only such duties and obligations with respect to each Member Property Account and Customer Account as are set forth in Article 8 of the UCC or otherwise mandated by Applicable Law.
Each Clearing Participant, including each FCM Clearing Participant, and each Customer acknowledges and agrees that the Clearinghouse is not a fiduciary for any Clearing Participant, including any FCM Clearing Participant, or Customer.
