= Axioms
:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:
:page-pagination:

:doctype: book

== Overview

1. The network is unreliable

2. Latency is non-zero

3. Bandwidth is definite

4. The network is unsecure

5. Topology does change

6. There are multiple administrators

7. Transport cost is non-zero

8. The network is heterogeneous


== Network Terms

[High Availability]
We define the term High Availability  in the common colloquial sense found in the database community where a database
is highly available if it can fail over to an active replica on the fly with no downtime, rather
than the definition of high availability used in the CAP theorem which requires that even minority
replicas remain available during a network partition.

[Service Level Agreement]
Data Integrity guarantees
Not the Data Availability Gguarantees

== Network Axioms

Data = Time

Data = Immutable

Time == Immutable

Latency != Availability

The structure of any system designed by an organization is isomorphic to the structure of the organization.
[Conways Law]

When a settled system is disturbed, it will adjust to diminish the change that has been made to it.
Any change in status quo prompts an opposing reaction in the responding system.
[Le Chatelier's principle]

=== Eight Fallacies of Distributed Computing

1. The network is reliable

2. Latency is zero

3. Bandwidth is infinite

4. The network is secure

5. Topology doesn't change

6. There is one administrator

7. Transport cost is zero

8. The network is homogeneous

https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing[source for "Eight Fallacies of Distributed Computing"]

[Ergodicity Section]
