---
version: 2.1
executors:
  python_executor:
    docker:
      - image: circleci/python:3.7.4
  node_executor:
    docker:
      - image: circleci/node:12.9.0-stretch
  shell_executor:
    docker:
      - image: circleci/buildpack-deps:buster-scm
  ruby_executor:
    docker:
      - image: circleci/ruby:2-stretch

jobs:
  build:
    executor: python_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "ci/requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ci/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "ci/requirements.txt" }}
      - run:
          name: Run MkDocs
          command: |
            . venv/bin/activate
            mkdocs build -s

 vale:
    executor: python_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v1.7.1
      - run:
          name: Run Vale
          command: |
            ./bin/vale --config ./ci/vale_styles/.vale.ini --glob='*.{md}' . | tee ./vale.out
      - store_artifacts:
          path: ./vale.out
         destination: ./vale.out

  linkchecker:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run markdown link checker
          command: |
            npm run test:links
      - save_cache:
          paths:
            - ./node_modules
          key: deps-{{ checksum "package.json" }}
      - store_artifacts:
          path: ./linkchecker.out
          destination: linkchecker.out

  markdownlint:
    executor: ruby_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install mdl
      - run:
          shell: /bin/bash #this is a non breaking command so it will always return success
          name: Run Markdownlint info checks
          command: |
            mdl --ignore-front-matter --style ./ci/markdownlint/info_style.rb . | tee ./markdownlint_info.out
      - run:
          name: Run Markdownlint
          command: |
            mdl --ignore-front-matter --style ./ci/markdownlint/style.rb . | tee ./markdownlint.out
      - store_artifacts:
          path: ./markdownlint.out
          destination: ./markdownlint.out
      - store_artifacts:
          path: ./markdownlint_info.out
          destination: ./markdownlint_info.out

workflows:
  version: 2
  default:
    jobs:
      - build
      - markdownlint
      - linkchecker