site_name: "Freight Trust Network"
site_description: "Documentation portal for Freight Trust Network"
site_author: "Freight Trust & Clearing"
site_url: "https://freighttrust.com"

repo_name: "freight-trust/omnibus"
repo_url: "https://github.com/freight-trust/omnibus/docs/"

# Copyright
copyright: "Copyright &copy; 2019-2020 FreightTrust and Clearing Corporation - All Rights Reserved"

nav: 

  - RuleBook:
      - Governing Laws: rulebook/0-governing-laws.md
      - General: rulebook/1-general.md
      - Governance: rulebook/2-governance.md
      - Network Participants: rulebook/3-network-clearing-participants.md
      - Delivery and Settlement: rulebook/4-delivery-and-settlement.md
      - Obligations: rulebook/5-obligations.md
      - Suspension: rulebook/6-suspension.md
      - Rules of Behavior: rulebook/rules-of-behavior.md
  - Blockchain:
      - Demateralizing Process: blockchain/dematerlizing-process.md
      - Virtual Machine: blockchain/evm.md
      - Network Topology: blockchain/topology.md
      - Token Mechanics: blockchain/token-mechanics.md
      - VBSM: blockchain/vbsm.md
  - Contracts:
      - Transporation: master-agreements/transporation-master-agreement-pro-shipper.md
      - Warehouse: warehouse/non-negotiable-bol.md
  - Corporate:
      - Bylaws: corporate/bylaws.md
      - Code of Conduct: corporate/code-of-conduct.md
      - CCPA: corporate/ccpa.md

# Configuration
theme:
  name: "material"
  language: "en"
  feature:
    tabs: true
  palette:
    primary: "black"
    accent: "deep-orange"

# Customization
extra:
  social:
    - type: "github"
      link: "https://github.com/freight-chain"
    - type: "twitter"
      link: "https://twitter.com/freighttrustnet"
    - type: "linkedin"
      link: "https://linkedin.com/company/freight-trust"

# Google Analytics
google_analytics:
  - ''
  - 'auto'
# Plug
plugins:
  - search
  - mkdocs-nav-enhancements

# Extensions
markdown_extensions:
  - admonition
  - smarty
  - meta
  - abbr
  - def_list
  - footnotes
# Extensions