= Neutral Legal Framework based upon Lex Meroatoria and the Common Law System
:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:
:page-pagination:

:doctype: book



== Overview

IncoTerms + UCC + UNICALDRIOT

To a lawyer, a legal contract has a distinct meaning:

A contract is an agreement giving rise to obligations which are enforced or recognised by law.
The

factor which distinguishes contractual from other legal obligations is that they are based on the

agreement of the contracting parties7.

For a contract to be valid, legal systems will impose certain requirements.
Under English law, there are four key elements that must (usually) be satisfied:

(i) one of the contracting parties must make

an offer to contract and the other(s) must accept that offer;

(ii) there must be '`consideration`' for the

offer, this being some form of value that must be exchanged;

(iii) the parties must have an intention to form legal relations;
and

(iv) there must be certainty as to terms of the contract.

EXAMPLE:

To a lawyer, a legal contract has a distinct meaning:

----
A contract is an agreement giving rise to obligations which are enforced or recognised by law. The
factor which distinguishes contractual from other legal obligations is that they are based on the
agreement of the contracting parties7.
For a contract to be valid, legal systems will impose certain requirements. Under English law, there
are four key elements that must (usually) be satisfied: (i) one of the contracting parties must make
an offer to contract and the other(s) must accept that offer; (ii) there must be ‘consideration’ for the
offer, this being some form of value that must be exchanged; (iii) the parties must have an intention
to form legal relations; and (iv) there must be certainty as to terms of the contract. Other systems of
law may have other requirements – for example, under New York law, many legal contracts must be
in writing and signed to become binding.

- ISDA, "Smart Contracts and
Distributed Ledger – A Legal
Perspective"
----

Other systems of law may have other requirements -- for example, under New York law, many legal contracts must be

in writing and signed to become binding.

Two Modes: National and International

|===
| Contract Function | Parties

| Master Covenant
| Mandatory, All Network Participants

| RuleBook Agreement
| Mandatory, All Commerical Orgs.

| Master Participation Agreement
| Mandatory for B2B

| Network Operator Agreement
| Mandatory for Node Operators

| Transactional Clauses
| Specific to Transaction Type

| Amendment Clauses
| Specific to Jurisdictional Area

| Business Terms and Conditions
| Unique to specific Business Entity

| Intergration Clause
| Mandatory, All Agreements
|===

National excludes lex mercatoria

----
Clause <#>  – Choice of law: lex mercatoria and Unidroit Principles

This contract is governed by general principles of law generally recognized in
international trade (lex mercatoria) together with the Unidroit Principles of
International Commercial Contracts (except for Articles 2.20, 3.2.7 and 6.2.1).
----

----
Clause <#> – Network Model Clause ?ref

This contract shall be governed by the law of [State X] interpreted and supplemented
by the Freight Trust Rule Book version <#>
----

----
Clause 6.1
“Any questions relating to this Agreement which are not expressly or implicitly settled
by the provisions contained in this Agreement shall be governed, in the following
order:
1) by the principles of law generally recognized in international trade as applicable to
international [type of contract: e.g., distributorship, licence] contracts,
2) by the relevant trade usages, and
3) by the Unidroit Principles of International Commercial Contracts,
with the exclusion of national laws.”
This clause, which is the most frequently used clause within the ICC model contracts,
states that the contract shall be governed by the lex mercatoria and the Unidroit
Principles and provides at the same time the following hierarchical order:
1. Contract provisions,
2. general principles of law applicable to the particular type of contract in question,
3. trade usages,
4. Unidroit Principles.
----
